### ISSUE TITLE
Compilation error after updating to 6.0.1

### ISSUE THREAD

**Issue by tkirby** [DaveWoodCom/XCGLogger#234]
After 'pod update' -> Installing XCGLogger 6.0.1 (was 5.0.1)

FileDestination.swift - line 95

Cannot convert value of type '[FileAttributeKey : Any]?' to expected argument type '[String : Any]?'

**Comment by DaveWoodCom** [comment]
Hi. This is the same issue as #232 & #233. It happens when you compile the library with Swift 3.x instead of 4.0. If you're still using Swift 3.x, please use 5.0.5.

If you're using CocoaPods, check the comments I've added to the #232 about the `post_install` hook you can add to your Podfile that should let you mix and match Swift 3.x and 4.0 libraries in the same project.

**Comment by filmhomage** [comment]
>  If you're still using Swift 3.x, please use 5.0.5.

Please put some release details to https://github.com/DaveWoodCom/XCGLogger/releases, when you release. Best
